<?php

/**
 * @file
 *  Module that contains helpful utility functions.
 */

require_once 'ffunctions.inc';

/**
 * Log a message to a file.
 *
 * @param mixed $mesage
 *  The message or data to log.
 */
function ffunctions_drupal_log_message($message) {
  if (!$log = variable_get('ffunctions_log', FALSE)) {
    $log = getcwd() . '/logs/test.log';
  }
  ffunctions_log_message($log, $message);
}

/**
 * Determine if an event is all day or not.
 *
 * @param array $date
 *  The loaded field date field data. This must include
 *  value, value2, timezone, timezone_db.
 * @param string $granularity
 *   (optional) The granularity of the date. Defaults to 'second'.
 *
 * @return boolean
 *  Whether or not this is an all day date.
 */
function ffunctions_date_is_all_day($date, $granularity = 'second') {
  if (!module_exists('date_all_day')) {
    return FALSE;
  }

  $format = 'Y-m-d H:i:s';
  $from = ffunctions_get_formatted_date($date['value'], $format, $date['timezone'], $date['timezone_db']);
  $to = $date['value'] == $date['value2'] ? $from :  ffunctions_get_formatted_date($date['value2'], $format, $date['timezone'], $date['timezone_db']);
  return date_is_all_day($from, $to, $granularity);
}
